import { Image, StyleSheet, Text, View } from 'react-native';

import { formatCurrency } from '@/lib/format';

const LOGO = require('@/assets/images/icon.png');
const APP_ICON = require('@/assets/images/app-icon.png');

export const SUMMARY_CARD_WIDTH = 360;

const NAVY = '#1e3a5f';

export type SummaryCategory = {
  name: string;
  amount: number;
  percent: number;
  color: string;
};

export function SummaryCard({
  bookName,
  totalIn,
  totalOut,
  net,
  categories,
  dateLabel,
}: {
  bookName: string;
  totalIn: number;
  totalOut: number;
  net: number;
  categories: SummaryCategory[];
  dateLabel: string;
}) {
  return (
    <View style={styles.card}>
      <View style={styles.top}>
        <Image source={APP_ICON} style={styles.topLogo} resizeMode="cover" />
        <View style={styles.topText}>
          <Text style={styles.watermark}>MyKhata Book</Text>
          <Text style={styles.bookName} numberOfLines={2}>
            {bookName || 'Book'}
          </Text>
          <Text style={styles.topSubtitle}>Monthly Summary</Text>
        </View>
      </View>

      <View style={styles.middle}>
        <View style={styles.stats}>
          <Stat label="Total In" value={totalIn} color="#16a34a" />
          <Stat label="Balance" value={net} color="#2563eb" />
          <Stat label="Total Out" value={totalOut} color="#dc2626" />
        </View>

        <View style={styles.divider} />

        <Text style={styles.heading}>Spending by Category</Text>
        {categories.length === 0 ? (
          <Text style={styles.emptyText}>No spending entries yet.</Text>
        ) : (
          categories.map((cat) => (
            <View key={cat.name} style={styles.catRow}>
              <View style={[styles.dot, { backgroundColor: cat.color }]} />
              <Text style={styles.catName} numberOfLines={1}>
                {cat.name}
              </Text>
              <View style={styles.barTrack}>
                <View
                  style={[
                    styles.barFill,
                    { width: `${Math.max(3, Math.min(100, cat.percent))}%`, backgroundColor: cat.color },
                  ]}
                />
              </View>
              <Text style={styles.catPercent}>{cat.percent}%</Text>
              <Text style={styles.catAmount} numberOfLines={1}>
                {formatCurrency(cat.amount)}
              </Text>
            </View>
          ))
        )}

        <View style={styles.divider} />

        <View style={styles.footer}>
          <Image source={LOGO} style={styles.logo} resizeMode="contain" />
          <Text style={styles.footerText}>Generated by MyKhata Book</Text>
          <Text style={styles.footerDate}>{dateLabel}</Text>
        </View>
      </View>
    </View>
  );
}

function Stat({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <View style={styles.stat}>
      <Text style={styles.statLabel}>{label}</Text>
      <Text style={[styles.statValue, { color }]} numberOfLines={1} adjustsFontSizeToFit>
        {formatCurrency(value)}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    width: SUMMARY_CARD_WIDTH,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  top: {
    backgroundColor: NAVY,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  topLogo: { width: 40, height: 40, borderRadius: 8, marginRight: 12 },
  topText: { flex: 1 },
  watermark: { fontSize: 11, fontWeight: '700', color: '#93c5fd', letterSpacing: 0.8 },
  bookName: { fontSize: 24, fontWeight: '800', color: '#ffffff', marginTop: 4, letterSpacing: -0.4 },
  topSubtitle: { fontSize: 12, fontWeight: '600', color: '#cbd5e1', marginTop: 4 },

  middle: { backgroundColor: '#ffffff', paddingHorizontal: 16, paddingTop: 16, paddingBottom: 14 },
  stats: { flexDirection: 'row', gap: 8 },
  stat: {
    flex: 1,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  statLabel: { fontSize: 10, fontWeight: '600', color: '#64748b', letterSpacing: 0.3 },
  statValue: { fontSize: 15, fontWeight: '800', marginTop: 4 },

  divider: { height: StyleSheet.hairlineWidth, backgroundColor: '#e2e8f0', marginVertical: 14 },

  heading: { fontSize: 13, fontWeight: '800', color: '#1e293b', marginBottom: 10 },
  emptyText: { fontSize: 12, color: '#94a3b8', fontStyle: 'italic' },

  catRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 9 },
  dot: { width: 8, height: 8, borderRadius: 4 },
  catName: { width: 68, fontSize: 11, fontWeight: '600', color: '#334155' },
  barTrack: { flex: 1, height: 8, borderRadius: 4, backgroundColor: '#eef2f7', overflow: 'hidden' },
  barFill: { height: 8, borderRadius: 4 },
  catPercent: { width: 32, fontSize: 11, fontWeight: '700', color: '#64748b', textAlign: 'right' },
  catAmount: { width: 74, fontSize: 11, fontWeight: '800', color: '#1e293b', textAlign: 'right' },

  footer: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  logo: { width: 24, height: 24, borderRadius: 6 },
  footerText: { flex: 1, fontSize: 10, fontStyle: 'italic', color: '#94a3b8' },
  footerDate: { fontSize: 10, fontWeight: '600', color: '#94a3b8' },
});
