import { Image, PixelRatio, StyleSheet, Text, View } from "react-native";

import { formatCurrency } from "@/lib/format";

const LOGO = require("@/assets/images/icon.png");
const APP_ICON = require("@/assets/images/app-icon.png");

const BASE_WIDTH = 360;

const TARGET_WIDTH_PX = 2160;

const SCALE = Math.max(1, TARGET_WIDTH_PX / (BASE_WIDTH * PixelRatio.get()));

const px = (n: number) => n * SCALE;

export const SUMMARY_CARD_WIDTH = px(BASE_WIDTH);

const NAVY = "#1e3a5f";

const TOP_LOGO_SIZE = px(76);
const TOP_LINE_GAP = px(2);
const TOP_LINE_1 = px(17);
const TOP_LINE_2 = px(35);
const TOP_LINE_3 = px(20);
const TOP_TEXT_HEIGHT =
  TOP_LINE_1 + TOP_LINE_2 + TOP_LINE_3 + TOP_LINE_GAP * 2;

export type SummaryCategory = {
  name: string;
  amount: number;
  percent: number;
  color: string;
};

export function SummaryCard({
  bookName,
  totalIn,
  totalOut,
  net,
  categories,
  dateLabel,
}: {
  bookName: string;
  totalIn: number;
  totalOut: number;
  net: number;
  categories: SummaryCategory[];
  dateLabel: string;
}) {
  return (
    <View style={styles.card}>
      <View style={styles.top}>
        <Image
          source={APP_ICON}
          style={styles.topLogo}
          resizeMode="contain"
          fadeDuration={0}
        />
        <View style={styles.topText}>
          <Text style={styles.watermark} numberOfLines={1}>
            MyKhata Book
          </Text>
          <Text style={styles.bookName} numberOfLines={1}>
            {bookName || "Book"}
          </Text>
          <Text style={styles.topSubtitle} numberOfLines={1}>
            Monthly Summary
          </Text>
        </View>
      </View>

      <View style={styles.middle}>
        <View style={styles.stats}>
          <Stat label="Total In" value={totalIn} color="#16a34a" />
          <Stat label="Balance" value={net} color="#2563eb" />
          <Stat label="Total Out" value={totalOut} color="#dc2626" />
        </View>

        <View style={styles.divider} />

        <Text style={styles.heading}>Spending by Category</Text>
        {categories.length === 0 ? (
          <Text style={styles.emptyText}>No spending entries yet.</Text>
        ) : (
          categories.map((cat) => (
            <View key={cat.name} style={styles.catRow}>
              <View style={[styles.dot, { backgroundColor: cat.color }]} />
              <Text style={styles.catName} numberOfLines={1}>
                {cat.name}
              </Text>
              <View style={styles.barTrack}>
                <View
                  style={[
                    styles.barFill,
                    {
                      width: `${Math.max(3, Math.min(100, cat.percent))}%`,
                      backgroundColor: cat.color,
                    },
                  ]}
                />
              </View>
              <Text style={styles.catPercent}>{cat.percent}%</Text>
              <Text style={styles.catAmount} numberOfLines={1}>
                {formatCurrency(cat.amount)}
              </Text>
            </View>
          ))
        )}

        <View style={styles.divider} />

        <View style={styles.footer}>
          <Image
            source={LOGO}
            style={styles.logo}
            resizeMode="contain"
            fadeDuration={0}
          />
          <Text style={styles.footerText}>Generated by MyKhata Book</Text>
          <Text style={styles.footerDate}>{dateLabel}</Text>
        </View>
      </View>
    </View>
  );
}

function Stat({
  label,
  value,
  color,
}: {
  label: string;
  value: number;
  color: string;
}) {
  return (
    <View style={styles.stat}>
      <Text style={styles.statLabel}>{label}</Text>
      <Text
        style={[styles.statValue, { color }]}
        numberOfLines={1}
        adjustsFontSizeToFit
      >
        {formatCurrency(value)}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    width: SUMMARY_CARD_WIDTH,
    backgroundColor: "#ffffff",
  },
  top: {
    backgroundColor: NAVY,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: px(16),
    paddingVertical: px(16),
  },
  topLogo: {
    width: TOP_LOGO_SIZE,
    height: TOP_LOGO_SIZE,
    marginRight: px(14),
  },
  topText: { flex: 1, height: TOP_TEXT_HEIGHT, justifyContent: "center" },
  watermark: {
    fontSize: px(12),
    lineHeight: TOP_LINE_1,
    includeFontPadding: false,
    fontWeight: "700",
    color: "#93c5fd",
    letterSpacing: px(0.8),
  },
  bookName: {
    fontSize: px(27),
    lineHeight: TOP_LINE_2,
    includeFontPadding: false,
    fontWeight: "800",
    color: "#ffffff",
    marginTop: TOP_LINE_GAP,
    letterSpacing: -px(0.4),
  },
  topSubtitle: {
    fontSize: px(14),
    lineHeight: TOP_LINE_3,
    includeFontPadding: false,
    fontWeight: "600",
    color: "#cbd5e1",
    marginTop: TOP_LINE_GAP,
  },

  middle: {
    backgroundColor: "#ffffff",
    paddingHorizontal: px(16),
    paddingTop: px(16),
    paddingBottom: px(14),
  },
  stats: { flexDirection: "row", gap: px(8) },
  stat: {
    flex: 1,
    backgroundColor: "#f8fafc",
    borderRadius: px(12),
    paddingVertical: px(10),
    paddingHorizontal: px(8),
    alignItems: "center",
  },
  statLabel: {
    fontSize: px(10),
    fontWeight: "600",
    color: "#64748b",
    letterSpacing: px(0.3),
  },
  statValue: { fontSize: px(15), fontWeight: "800", marginTop: px(4) },

  divider: { height: 1, backgroundColor: "#e2e8f0", marginVertical: px(14) },

  heading: {
    fontSize: px(13),
    fontWeight: "800",
    color: "#1e293b",
    marginBottom: px(10),
  },
  emptyText: { fontSize: px(12), color: "#94a3b8", fontStyle: "italic" },

  catRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: px(8),
    marginBottom: px(9),
  },
  dot: { width: px(8), height: px(8), borderRadius: px(4) },
  catName: {
    width: px(68),
    fontSize: px(11),
    fontWeight: "600",
    color: "#334155",
  },
  barTrack: {
    flex: 1,
    height: px(8),
    borderRadius: px(4),
    backgroundColor: "#eef2f7",
    overflow: "hidden",
  },
  barFill: { height: px(8), borderRadius: px(4) },
  catPercent: {
    width: px(32),
    fontSize: px(11),
    fontWeight: "700",
    color: "#64748b",
    textAlign: "right",
  },
  catAmount: {
    width: px(74),
    fontSize: px(11),
    fontWeight: "800",
    color: "#1e293b",
    textAlign: "right",
  },

  footer: { flexDirection: "row", alignItems: "center", gap: px(6) },
  logo: { width: px(24), height: px(24) },
  footerText: {
    flex: 1,
    fontSize: px(10),
    fontStyle: "italic",
    color: "#94a3b8",
  },
  footerDate: { fontSize: px(10), fontWeight: "600", color: "#94a3b8" },
});
